name: linter

on: [push, pull_request]

jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.19]
        platform: [ubuntu-latest]
        working-directory:
          - ""
          - example
    runs-on: ${{ matrix.platform }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: golangci-lint ${{ matrix.working-directory }}
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.50.1
          working-directory: ${{ matrix.working-directory}}
          args: --verbose
